[NAMGFL]
YCPF_NLNREQIN = 0
YDAL_NLLADV = true
YDAL_NLLGP = true
YDAL_NLLQM = false
YDAL_NLLQMH = false
YDAL_NLLREQOUT = false
YDAL_NLLSLHD = false
YDAL_NLNREQIN = 0
YDOM_NLLADV = true
YDOM_NLLGP = true
YDOM_NLLQM = false
YDOM_NLLQMH = false
YDOM_NLLREQOUT = false
YDOM_NLLSLHD = false
YDOM_NLNREQIN = 0
YI_NLLADV = true
YI_NLLGP = true
YI_NLLGPINGP = false
YI_NLLQM = false
YI_NLLQMH = false
YI_NLLREQOUT = true
YI_NLLSLHD = true
YI_NLLSP = false
YI_NLNCOUPLING = 0
YI_NLNREQIN = 1
YL_NLLADV = true
YL_NLLGP = true
YL_NLLGPINGP = false
YL_NLLQM = false
YL_NLLQMH = false
YL_NLLREQOUT = true
YL_NLLSLHD = true
YL_NLLSP = false
YL_NLNCOUPLING = 0
YL_NLNREQIN = 1
YQ_NLLADV = true
YQ_NLLGP = false
YQ_NLLGPINGP = false
YQ_NLLHV = false
YQ_NLLQM = false
YQ_NLLQMH = false
YQ_NLLREQOUT = true
YQ_NLLSLHD = true
YQ_NLLSP = true
YQ_NLLVSPLIP = false
YQ_NLNREQIN = 1
YRKTH_NLLGP = true
YRKTH_NLLREQOUT = false
YRKTH_NLNREQIN = -1
YRKTH_NLREFVALI = 0
YRKTQC_NLLGP = true
YRKTQC_NLLREQOUT = false
YRKTQC_NLNREQIN = -1
YRKTQC_NLREFVALI = 0
YRKTQV_NLLGP = true
YRKTQV_NLLREQOUT = false
YRKTQV_NLNREQIN = -1
YRKTQV_NLREFVALI = 0
YR_NLLADV = true
YR_NLLGP = true
YR_NLLGPINGP = false
YR_NLLQM = false
YR_NLLQMH = false
YR_NLLREQOUT = true
YR_NLLSLHD = false
YR_NLLSP = false
YR_NLNCOUPLING = 0
YR_NLNREQIN = 1
YSPF_NLNREQIN = 0
YS_NLLADV = true
YS_NLLGP = true
YS_NLLGPINGP = false
YS_NLLQM = false
YS_NLLQMH = false
YS_NLLREQOUT = true
YS_NLLSLHD = false
YS_NLLSP = false
YS_NLNCOUPLING = 0
YS_NLNREQIN = 1
YTKE_NLLADV = true
YTKE_NLLCDERS = false
YTKE_NLLGP = true
YTKE_NLLGPINGP = false
YTKE_NLLHV = false
YTKE_NLLPT = false
YTKE_NLLQM = false
YTKE_NLLQMH = false
YTKE_NLLREQOUT = true
YTKE_NLLSLHD = true
YTKE_NLLSP = false
YTKE_NLLT5 = false
YTKE_NLLVSPLIP = false
YTKE_NLNCOUPLING = 0
YTKE_NLNREQIN = 0
YUAL_NLLADV = true
YUAL_NLLGP = true
YUAL_NLLQM = false
YUAL_NLLQMH = false
YUAL_NLLREQOUT = false
YUAL_NLLSLHD = false
YUAL_NLNREQIN = 0
YUNEBH_NLLGP = true
YUNEBH_NLLREQOUT = false
YUNEBH_NLNREQIN = 0
YUOM_NLLADV = true
YUOM_NLLGP = true
YUOM_NLLQM = false
YUOM_NLLQMH = false
YUOM_NLLREQOUT = false
YUOM_NLLSLHD = false
YUOM_NLNREQIN = 0

[NAMPHY]
LAERODES = true
LAEROLAN = true
LAEROSEA = true
LAEROSOO = true

[NAMPHY0]
EDD = 1.0
USURIC = 1.0
USURICE = 0.5
USURICL = 4.0
USURID = 0.048
USURIDE = 0.25
VZIUSTAR0 = 12.0

[NAMDYNA]
LSLHD_GFL = true
