[NAERAD]
LRRTM = true
LSRTM = false
NAER = 1
NOVLP = 6
NOZOCL = 2
NRADFR = "ZNRADFR"
NSW = 6

[NAMAFN]
TFP_UCLNAME = "WIND.U.PHYS"
TFP_VCLNAME = "WIND.V.PHYS"
TFP_ICLNAME = "SOLID_WATER"
TFP_LCLNAME = "LIQUID_WATER"
GFP_CLSSCLNAME = "SURFACCNEIGE"
GFP_CLSPCLNAME = "SURFACCPLUIE"
GFP_CLSGCLNAME = "SURFACCGRAUPEL"
GFP_XLSSCLNAME = "SURFINSNEIGE"
GFP_XLSPCLNAME = "SURFINSPLUIE"
GFP_XLSGCLNAME = "SURFINSGRAUPEL"

[NAMARPHY]
LKFBCONV = false
LKFBD = false
LKFBS = false
LMFSHAL = true
LMICRO = true
LMPA = true
LMSE = true
LTURB = true

[NAMCFU]
LCUMFU = true
LFPLS = true
LFPLSG = true
LFR = true
LFRRC = true
LFSF = true
LNEBPAR = true
LNEBTT = true
LRAYD = true
LRAYS = true

[NAMCHK]
LECHKEVO = false
LECHKTND = false
LECHKPS = false

[NAMCT0]
LAROME = true
LMSGINIT = false
LNHDYN = true
LSPRT = true
LTWOTL = true
NFRHIS = 1
NFRSDI = 15

[NAMDYN]
LADVF = true
LQMPD = false
LQMT = false
LQMVD = false
NSITER = 0
NSPDLAG = 3
NSVDLAG = 3
NTLAG = 3
NVLAG = 3
NWLAG = 3
RDAMPDIV = 20.0
RDAMPPD = 200000.0
RDAMPQ = 20.0
RDAMPT = 20.0
RDAMPVD = 20.0
RDAMPVOR = 20.0
REPS1 = 0.0
REPS2 = 0.0
REPSM1 = 0.0
REPSM2 = 0.0
REPSP1 = 0.0
SIPR = 90000.0
SLHDA0 = 0.25
SLHDD00 = 6.5e-5
VESL = 0.0
XIDT = 0.0
ZSLHDP1 = 1.7
ZSLHDP3 = 0.6

[NAMDYNA]
LCOMADH = true
LCOMADV = false
LCOMAD_W = true
LCOMAD_T = true
LCOMAD_SPD = true
LCOMAD_SVD = true
LCOMAD_SP = true
LCOMAD_GFL = true
LGRADSP = "LGRADSP"
LGWADV = false
LNESC = false
LPC_FULL = false
LRDBBC = true
LSETTLS = true
LSETTLST = true
LSLHD_OLD = true
LSLHD_SPD = false
LSLHD_SVD = false
LSLHD_T = false
LSLHD_W = false
LSLHD_GFL = true
NDLNPR = 1
NPDVAR = 2
NVDVAR = 4
SLHDEPSH = 0.0025

[NAMGFL]
NGFL_EZDIAG = 3
YA_NLLPT = false
YA_NLLREQOUT = "LCLOUDFRACTI"
YA_NLNREQIN = "ICLOUDFRACTI"
YEZDIAG_NL1CNAME = "EZDIAG01"
YEZDIAG_NL1LREQOUT = false
YEZDIAG_NL2CNAME = "EZDIAG02"
YEZDIAG_NL2LREQOUT = false
YEZDIAG_NL3CNAME = "EZDIAG03"
YEZDIAG_NL3LREQOUT = false
YG_NLLPT = false
YG_NLLQM = true
YG_NLLSLHD = true
YG_NLNCOUPLING = -1
YG_NLREFVALC = 0.0
YG_NLNREQIN = 1
YI_NLLPT = false
YI_NLLQM = true
YI_NLLSLHD = true
YI_NLNCOUPLING = -1
YI_NLREFVALC = 0.0
YI_NLNREQIN = 1
YL_NLLPT = false
YL_NLLQM = true
YL_NLLSLHD = true
YL_NLNCOUPLING = -1
YL_NLREFVALC = 0.0
YL_NLNREQIN = 1
YQ_NLLCOMAD = true
YQ_NLLPT = false
YQ_NLLQM = true
YQ_NLLSLHD = false
YQ_NLNCOUPLING = 1
YQ_NLNREQIN = 1
YR_NLLPT = false
YR_NLLQM = true
YR_NLLSLHD = true
YR_NLNCOUPLING = -1
YR_NLREFVALC = 0.0
YR_NLNREQIN = 1
YSRC_NLLPT = false
YS_NLLPT = false
YS_NLLQM = true
YS_NLLSLHD = true
YS_NLNCOUPLING = -1
YS_NLREFVALC = 0.0
YS_NLNREQIN = 1
YTKE_NLLPT = false
YTKE_NLNCOUPLING = 0
YTKE_NLNREQIN = "ITKE"

[NAMPARAR]
CMF_UPDRAFT = "DUAL"
CMF_CLOUD = "STAT"
LMIXUV = true
LLCRIT = true
LTOTPREC = false
LOLSMC = true
LOTOWNC = true
LOSEDIC = true
LOSIGMAS = true
LOSUBG_COND = true
NPRINTFR = 10000
NPTP = 1
VSIGQSAT = 0.02
LOCND2 = true
RFRMIN1 = 1e-5
RFRMIN2 = 1e-8
RFRMIN3 = 3e-7
RFRMIN4 = 3e-7
RFRMIN7 = 0.0
LKOGAN = true
RADSN = 1.0
RADGR = 0.5
LSTATNW = "$LSTATNW"
LHARATU = "$LHARATU"

[NAMPHY]
LAERODES = true
LAEROLAN = true
LAEROSEA = true
LAEROSOO = true
LMPHYS = true
LO3ABC = true
LRAYFM = true
LHLRADUPD = true

[NAMPHY0]
ALMAV = 300.0
BEDIFV = 0.05
ECMNP = 3000.0
GCCSV = 0.0
GCVADS = 0.8
GCVALFA = 4.5e-5
GCVBETA = 0.2
GCVMLT = 0.00016
GCVNU = 2.5e-5
GCVPSI = 1.0
GCVPSIE = 1.0
GDDEVA = 0.25
GDDSDE = 0.5
GWDCD = 6.0
HUCOE = 0.5
HUTIL = 1.8
QSSC = 400.0
QSSUSC = 0.75
QSSUSS = 0.4
QSSUSV = 250.0
QSUSXC = 0.0002
QSUSXS = 0.0003
QXRAL = 130.0
QXRDEL = 0.49
QXRHX = 0.99
QXRR = 0.25
RCVEVAP = 0.25
REVGSL = 15.0
SCO = -20.0
TDDGP = 0.8
TENTR = 2.5e-6
TENTRX = 8e-5
TUDGP = 0.8
UHDIFV = 0.0008
USURIC = 0.175
USURICE = 0.5
USURICL = 1.0
USURID = 0.1
USURIDE = 0.25
VZ0CM = 0.00015
XMAXLM = 5000.0
XMINLM = 10.0

[NAMPHY1]
ALBMIN = 0.65
ALCRIN = 0.75
GCGEL = 3e-5
GCGELS = 5e-5
GNEIMX = 1.8
GNEIMXS = 1.8
RCTVEG3 = 1.2e-5
RCTVEG4 = 1e-5

[NAMPHY2]
FACRAF = 3.5
HTKERAF = 20.0
LMULAF = true
LRAFTKE = true
LRAFTUR = true
XDAMP = 1.0
XMULAF = -1.85
LWMOCLOUD = true

[NAMSPSDT]
LSPSDT = "$LSPSDT?.FALSE."
NSCALES_SDT = 1
SDEV_SDT1 = "$SDEV_SDT?0.50"
TAU_SDT1 = "$TAU_SDT?28800"
XLCOR_SDT1 = "$XLCOR_SDT?500000"
XCLIP_RATIO_SDT = "$XCLIP_RATIO_SDT?2.0"
CSPEC_SHAPE_SDT = "WeaverCourtier1"
LWRITE_ARP = false
LSPG_SDT = "$LSPG_SDT?.FALSE."
SPGQ_SDT = "$SPGQ_SDT?0.5"
SPGLAMBDA_SDT = "$SPGLAMBDA_SDT?-999.0"
SPGMU_SDT = "$SPGMU_SDT?-999.0"
SPGSIGMA_SDT = "$SPGSIGMA_SDT?-999.0"
SPGADTMIN_SDT = "$SPGADTMIN_SDT?0.1"
SPGADTMAX_SDT = "$SPGADTMAX_SDT?3.0"

[NAMSTOPH]
LFORCENL = "LFORCENL"
NFORCESTART = 0
NFORCEEND = 1
AMAGSTOPH = 1.0

[NAMTOPH]
ETCVIM = 5000.0
ETNEBU = 5000.0
ETPLUI = 5000.0
XDRMTK = 6e-7
XDRMTP = 800.0
XDRMUK = 3e-7
XDRMUP = 800.0

[NAMTRANS0]
RDISTR_E = 1.0

[NAMXFU]
LXCLP = true
LXCLS = true
LXFU = true
LXNEBPA = true
LXNEBTT = true
LXPLS = true
LXPLSG = true
LXQCLS = true
LXR = true
LXXGST = true
LXTHW = true
LXTRT = true
LXXDIAGH = true
LXTTCLS = true
NXGSTPERIOD = "$NXGSTPERIOD"
NFRRAZ = 1
NRAZTS = "NRAZTSLIST"

[NEMELBC0A]
LESPCPL = false
