[NAMARG]
NCONF = 923
CNMEXP = "CLIM"
CUSTOP = "t0"
TSTEP = 600.0
LSLAG = true
NSUPERSEDE = 0

[NAMCT0]
LRPLANE = true
LALLOPR = false

[NAMMCC]
N923 = 0

[NAMPHY]
LMPHYS = true
LSOLV = true
LVGSN = true

[NAMPHY0]
GCVPSI = 0.0

[NEMDIM]
NBZONG = 8
NBZONL = 8
