[NAMDIM]
NPROMA = "$NPROMA"

[NAMFPSC2]
NFPROMA = "$NPROMA"

[NAMFPSC2_DEP]
NFPROMA_DEP = "$NPROMA"

[NAMJFH]
N_VMASS = 0

[NAMPAR0]
MBX_SIZE = 628000000
LMPOFF = "$LMPOFF"
LOPT_SCALAR = true

[NAMPAR1]
NCOMBFLEN = 8000000
L_GATHERV_WRGP = "$L_GATHERV_WRGP"
