[NAMAFN]
GFP_CLSGCLNAME = "SURFACCGRAUPEL"
GFP_CLSPCLNAME = "SURFACCPLUIE"
GFP_CLSSCLNAME = "SURFACCNEIGE"
TFP_QLLGP = true

[NAMCFU]
LFPLSG = true

[NAMCT0]
LAROME = true
LNHDYN = true
LSPRT = true

[NAMDYNA]
NDLNPR = 1

[NAMGFL]
YL_NLNREQIN = 1
YI_NLNREQIN = 1
YR_NLLGP = true
YR_NLLSP = false
YR_NLNREQIN = 1
YS_NLLGP = true
YS_NLLSP = false
YS_NLNREQIN = 1
YG_NLLGP = true
YG_NLLSP = false
YG_NLNREQIN = 1
YQ_NLLGP = true
YQ_NLLSP = false
