[NAMVARBC_RAD]
LBC_RAD = true
"yconfig(3,5)%nparam" = 10
"yconfig(3,5)%npredcs(1:10)" = "0,1,2,8,9,10,15,16,17,18"
"yconfig(3,6)%nparam" = 5
"yconfig(3,6)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(3,7)%nparam" = 5
"yconfig(3,7)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(3,8)%nparam" = 5
"yconfig(3,8)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(3,9)%nparam" = 5
"yconfig(3,9)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(3,10)%nparam" = 5
"yconfig(3,10)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(4,2)%nparam" = 4
"yconfig(4,2)%npredcs(1:4)" = "0,8,9,10"
"yconfig(4,3)%nparam" = 5
"yconfig(4,3)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(4,4)%nparam" = 5
"yconfig(4,4)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(4,5)%nparam" = 5
"yconfig(4,5)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(15,2)%nparam" = 4
"yconfig(15,2)%npredcs(1:4)" = "0,8,9,10"
"yconfig(15,3)%nparam" = 5
"yconfig(15,3)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(15,4)%nparam" = 5
"yconfig(15,4)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(15,5)%nparam" = 5
"yconfig(15,5)%npredcs(1:5)" = "0,1,8,9,10"
"yconfig(16,5)%nparam" = 5
"yconfig(16,5)%npredcs(1:5)" = "0,1,8,9,10"
nbg_AMSUA = 2000
nbg_AMSUB = 2000
nbg_MHS = 2000
nbg_IASI = 2000

[NAMVARBC_AIREP]
LBC_AIREP = false
LBC_AMDAR = false
LBC_ACARS = false
LBC_COLBA = false
LBC_CODAR = false

[NAMVARBC_SFCOBS]
LBC_SFCOBS_PS = false
LBC_SFCOBS_APD = true
nbg_sfcobs_min_apd = 15
nbg_sfcobs_ndays_apd = 15
nbg_sfcobs_min_ps = 15
nbg_sfcobs_ndays_ps = 15
